### PR TITLE
Change Library to Coffeescript and use Amazon's JS SDK

### PR DESCRIPTION
**Pull request by MattCBowman**
- Convert existing code to Coffeescript
- Add grunt file to compile Coffeescript to JS
- Update `package.json` to have `#.#.x` version dependency referencing
- Update readme file to reflect changes

### CODE REVIEW

**Comment by jesseditson** [comment]
Wow! I don't use this in production anymore, so I appreciate the monster PR - do you mind if I make you a contributor on this repo?

**Comment by MattCBowman** [comment]
Sure - I was hoping that I wouldn't freak you out with such a large PR. Most of the logic has remained the same, just switched out to the AWS SDK because they offer some really nice auth'ing if you run your stuff on EC2 w/ an IAM role. :smile:

**Comment by jesseditson** [comment]
Awesome. I can add you to the npm owners as well so you can publish there if you like. Always happy to see projects resurrected! What's your npm username? (`npm whoami`)

**Comment by MattCBowman** [comment]
mbowman

**Comment by jesseditson** [comment]
Cool - merged up, feel free to publish a version at your leisure! (this repo is `winston-sns` on npm)

**Pull request merged**
